/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package latihan;

 
class Test <T>{
    T obj;
    Test(T obj) {
        this.obj = obj;

    }
    public T getObject(){
        return this.obj;
    }
}
 class Main {
    public static void main(String [] args) 
    {
       Test<Integer> iObj = new Test<Integer>(15);
       System.out.println(iObj.getObject());

       Test<String> sObj = new Test<String>("GeeksForGeeks");
       System.err.println(sObj.getObject());
    }
}

