/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package serialisasi;

import java.io.*;


   class Demo implements java.io.Serializable{
       public int a;
       public String b;

       //konstruktor default
       public Demo (int a, String b){
           this.a = a;
           this.b = b;
       }

        public static void main(String[] args)
     {
        Demo object = new Demo(1, "geeksforgeeks");
        String filename = "file.ser";

        //serialization
        try {
            //menyimpan objek dalam sebuah file
            FileOutputStream file = new FileOutputStream(filename);
            ObjectOutputStream out = new ObjectOutputStream(file);
            
            //Metod untuk serialization dari objek
            out.writeObject(object);

            out.close();
            file.close();

            System.out.println("Objek sudah diserialisasi");
            
        } catch (IOException ex) {
            //TODO: handle exception
            System.out.println("IOException sudah tertangkap");
        }

        Demo object1 = null;

        //Deserialisasi

        try {
        // Membaca objek dari sebuah file
        FileInputStream file = new FileInputStream(filename);
        ObjectInputStream in = new ObjectInputStream(file);

        //Metodde untuk deserialisasi objek
        object1 = (Demo)in.readObject();

        in.close();
        file.close();
        System.out.println("Objek sudah diserialisasi");
        System.out.println("a =" + object1.a);
        System.out.println("b =" + object1.b);
        } catch (IOException ex) {
            //TODO: handle exception
            System.out.println("IOException sudah tertangkap");
        }

        catch (ClassNotFoundException ex){
            System.out.println("ClassNotFoundException sudah tertangkap");
        }
        


        }
        
    }

