/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package perpus;

import java.util.List;

public class App {
    public static void main(String[] args) {
       Buku buku = new Buku();
       mahasiswa mhs = new mahasiswa();
       pinjam pj = new pinjam();

       mhs.setNim(17523184);
       mhs.setName("Natasya Ulfha Nabilla");

       buku.setJudul("Filosofi teras");
       buku.setPengarang("Henry Manampiring");
       buku.setTahun("2020");

       pj.meminjam(mhs, buku);
       pj.lihatPeminjaman();

    }
}
