/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package serialdandeserialisasi;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.io.Serializable;

class Emp implements Serializable {
        private static final long serialversionUID = 129348938L;
        transient int a;
        static int b;
        String name;
        int age; 

        //konstruktor default
        public Emp (String name, int age, int a, int b ){
            this.name = name;
            this.age= age;
            this.a=a;
            this.b=b;

        }
    }
        public class SerialExample{
            public static void printdata (Emp object1){
                System.out.println("name = "+object1.name);
                System.out.println("age = " +object1.age);
                System.out.println("a = " +object1.a);
                System.out.println("b = " + object1.b);
       }
        public static void main(String[] args) {
            Emp object = new Emp ("ab", 20, 2, 1000);
            String filename = "tasya.txt";

            //serialization
            try {
                FileOutputStream file = new FileOutputStream(filename);
                ObjectOutputStream out = new ObjectOutputStream(file);

                // Metode untuk serialisasi objek

                out.writeObject(object);

                out.close();
                file.close();


                System.out.println("Objek sudah disearialisasi\n" +"Data sebeleum Deserialisasi");
                printdata(object);

                //nilai statik varibael diganti
                object.b =2000;

                
            } catch (IOException ex) {
                //TODO: handle exception
                System.out.println("IOException is caught");

            }
            object = null;
            //Deserialisasi
            try {
                FileInputStream file = new FileInputStream (filename);
                ObjectInputStream in = new ObjectInputStream(file);

                object = (Emp)in.readObject();
                in.close();
                file.close();
                System.out.println("Object has been deserialized\n" +
                "Data after Deserialization");
                printdata(object);
            } catch (IOException ex) {
                //TODO: handle exception
                System.out.println("IOException is caught");
            }
            catch(ClassNotFoundException ex){
                System.out.println("ClassNotFoundException" + "is caught");
            }

    
    }
}
