/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package designpattern;

public class FactoryPatternDemo{
    public static void main(String[] args) {
        ShapeFactory shapeFactory = new ShapeFactory();

        //get an object of Circle and call its draw method
        Shape shape1= shapeFactory.getShape("CIRCLE");
        //call draw method of circle
        shape1.draw();

        //get an object of Rectangl and call its draw method
        Shape shape2 = shapeFactory.getShape("RECTANGLE");
        //call draw method of rectangle
        shape2.draw();

         //get an object of Squaree and call its draw method
         Shape shape3 = shapeFactory.getShape("SQUARE");
         //call draw method of rectangle
         shape3.draw();


       
    }
}
