/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cobaKoleksi;
import java.util.*;

public class CollectionsDemo {
    public static void main(String[] args) {
        //ArrayList
        List a1 = new ArrayList();
        a1.add ("Tasya");
        a1.add("Ulfha");
        a1.add("Nabilla");
        System.out.println("ArrayList Elements");
        System.out.println("\t" + a1);

        //LinkedList
        List l1 = new LinkedList();
        l1.add("Tasya");
        l1.add("Ulfha");
        l1.add("Nabilla");
        System.out.println();
        System.out.println("LinkedList Elements");
        System.out.println("\t" + l1);

        //HashSet
        Set s1 = new HashSet();
        s1.add("Tasya");
        s1.add("Ulfha");
        s1.add("Nabilla");

        //Hashmap
        Map m1 = new HashMap();
        m1.put("Tasya", "21");
        m1.put("Ulfha", "22");
        m1.put("Nabilla" , "23");

        System.out.println();
        System.out.println("Map elements");
        System.out.println("\t" + m1);


        
    }
}
